### ISSUE TITLE
`monit unmonitor memcached` also unmonitors `poll_memcached`...

### ISSUE THREAD

**Issue by mirw** [Metaswitch/clearwater-monit#16]
...but `monit monitor memcached` does *not* re-monitor `poll_memcached`.  As a result, you may end up with health-checks not being run.

It looks like this is a result of the recent change to use `depends on` rules.

**Comment by eleanor-merry** [comment]
I'd like to fix this by moving to using groups (https://mmonit.com/monit/documentation/monit.html#SERVICE-GROUPS). 

With groups, all memcached checks would be part of the memcached_group (e.g. add group memcached_group to the monit file) and the recommended command would change to monit un|monitor -g memento_group

**Comment by mirw** [comment]
How do we stop someone from typing `monit unmonitor memcached` and still breaking things?  It is documented in previous versions, so we risk someone reading the wrong version of the docs and ending up breaking their system.

(Maybe we need to change the name of the processes themselves too?)

**Comment by bossmc** [comment]
Maybe we should change to call the group `memcached` and the existing `memcached` process `memcached_core` or similar.  That way you use the shorter name to monitor/unmonitor processes, but if you forget to pass `-g` you'll get an error rather than incorrect behaviour?

**Comment by eleanor-merry** [comment]
Ok, I'll change the name of the process. This means that running the old command (without passing -g) gives the error "Action failed -- There is no service by that name".
