### ISSUE TITLE
DEB_VERSION_QUALIFIER ignored in latest clearwater.mk

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/clearwater-monit#29]
In previous versions I've been able to add a unique qualifier to the version number of the deliverable package, but this has been broken in the latest version. BTW - Other repositories still honor the DEB_VERSION_QUALIFIER environment variable.

**Comment by graemerobertson** [comment]
@eleanor-merry, (aka 'Cloud User'?), can you comment?

**Comment by eleanor-merry** [comment]
Fixed by https://github.com/Metaswitch/clearwater-monit/pull/28 (and I'd accidentally removed it in https://github.com/Metaswitch/clearwater-monit/pull/25)
