### ISSUE TITLE
Monit fails to start the ralf process

### ISSUE THREAD

**Issue by sathiyan-sivathas** [Metaswitch/clearwater-monit#41]
When a deployment is spun up where the ralf process is present, monit fails to start this process.  There's nothing wrong with the process itself since you can start it manually using `sudo service ralf start`.

There are some differences in the `/etc/monit/conf.d/ralf.monit` script compared to the other processes which could be worth investigating.

**Comment by rkd-msw** [comment]
Duplicate of https://github.com/Metaswitch/ralf/issues/238#issuecomment-238832647?

**Comment by sathiyan-sivathas** [comment]
Yep, I'll close this as a duplicate.
