### ISSUE TITLE
Monit commands to stop monitoring and kill a group of processes don't work on the latest OVAs

### ISSUE THREAD

**Issue by AME2** [Metaswitch/clearwater-monit#46]
I've been doing some testing of the etcd cluster recovery process. At the beginning of the process you must get monit to stop monitoring the clearwater-etcd process and kill them.

Currently the etcd recovery MOP instructs you to run the following commands:

```
sudo monit stop –g etcd
sudo monit stop –g clearwater_cluster_manager
sudo monit stop –g clearwater_config_manager
sudo monit stop –g clearwater_queue_manager
```

However these commands do not work on the latest OVAs (built on Jan12):

```
clearwater@ame2-sprout-1:/tmp/patch$ sudo monit stop –g etcd
There is no service named "%E2%80%93g"
clearwater@ame2-sprout-1:/tmp/patch$ sudo monit stop –g clearwater_cluster_manager
There is no service named "%E2%80%93g"
clearwater@ame2-sprout-1:/tmp/patch$ sudo monit stop –g clearwater_config_manager
There is no service named "%E2%80%93g"
clearwater@ame2-sprout-1:/tmp/patch$ sudo monit stop –g clearwater-config-manager
There is no service named "%E2%80%93g"
```

I used the following OVAs for this testing:

CC-homestead,homestead-prov-10.0.0-170112-~255.00.0.ova
CC-ralf-10.0.0-170112-~255.00.0.ova
CC-sprout-10.0.0-170112-~255.00.0.ova

**Comment by eleanor-merry** [comment]
Does `sudo monit stop -g sprout` work?

**Comment by AME2** [comment]
Yes

**Comment by AME2** [comment]
This turned out to be an issue with with copying and pasting the dash from Word. The commands work fine when typed out into the terminal.
